import express, { Request, Response } from 'express';
import { authMiddleware, AuthRequest } from '../middleware/auth';
import { DocumentService } from '../../services/DocumentService';
import { logger } from '../../utils/logger';

const router = express.Router();

router.use(authMiddleware);

router.get('/documents/:id', async (req: AuthRequest, res: Response) => {
  try {
    const documentService = new DocumentService(global.db);
    const documentId = req.params.id as string;
    const userId = req.user!.id;
    const { format } = req.query;

    const document = await documentService.getDocument(documentId, userId);
    
    if (format === 'markdown') {
      res.setHeader('Content-disposition', `attachment; filename=${document.title || 'document'}.md`);
      res.setHeader('Content-type', 'text/markdown');
      res.send(`# ${document.title}\n\n${document.description || ''}`);
    } else if (format === 'pdf') {
      // Return HTML for PDF so user can use Browser Print (Most reliable on Render free tier)
      res.setHeader('Content-type', 'text/html');
      res.send(`
        <html>
          <head>
            <title>${document.title}</title>
            <style>
              body { font-family: sans-serif; padding: 40px; line-height: 1.6; }
              h1 { border-bottom: 2px solid #eee; padding-bottom: 10px; }
            </style>
          </head>
          <body>
            <h1>${document.title}</h1>
            <p>${document.description || 'No description available.'}</p>
            <div style="margin-top: 40px; color: #666; font-size: 12px; border-top: 1px solid #eee; padding-top: 20px;">
              Generated by Nordic Slate Editor
            </div>
            <script>window.print();</script>
          </body>
        </html>
      `);
    } else if (format === 'docx') {
      res.setHeader('Content-disposition', `attachment; filename=${document.title || 'document'}.docx`);
      res.setHeader('Content-type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
      res.send(`${document.title}\n\n${document.description || ''}`);
    } else {
      res.status(400).json({ error: 'Unsupported format' });
    }
  } catch (error) {
    logger.error(`Error exporting document: ${error}`);
    res.status(500).json({ error: 'Failed to export document' });
  }
});

export default router;
