import express, { Request, Response } from 'express';
import { authMiddleware, AuthRequest } from '../middleware/auth';
import { DocumentService } from '../../services/DocumentService';
import { logger } from '../../utils/logger';

const router = express.Router();

router.use(authMiddleware);

router.get('/documents/:id', async (req: AuthRequest, res: Response) => {
  try {
    const documentService = new DocumentService(global.db);
    const documentId = req.params.id as string;
    const userId = req.user!.id;
    const { format } = req.query;

    const document = await documentService.getDocument(documentId, userId);
    
    if (format === 'markdown') {
      res.setHeader('Content-disposition', `attachment; filename=${document.title || 'document'}.md`);
      res.setHeader('Content-type', 'text/markdown');
      res.send(`# ${document.title}\n\n${document.description || ''}`);
    } else if (format === 'pdf') {
      // Return HTML for PDF so user can use Browser Print (Most reliable on Render free tier)
      res.setHeader('Content-type', 'text/html');
      
      // Basic support for our custom resizable image in export
      const contentHtml = typeof document.content === 'string' ? document.content : 
                          (document.content && document.content.html ? document.content.html : document.description || '');

      res.send(`
        <html>
          <head>
            <title>${document.title}</title>
            <style>
              body { font-family: 'Inter', sans-serif; padding: 50px; line-height: 1.6; color: #1e293b; max-width: 800px; margin: 0 auto; }
              h1 { border-bottom: 2px solid #f1f5f9; padding-bottom: 15px; font-size: 2.5rem; margin-bottom: 30px; }
              
              /* Support for our Resizable Images in Export */
              .resizable-image-container { 
                display: block; 
                margin: 20px auto; 
                text-align: center;
                width: fit-content;
              }
              .resizable-image-container img { 
                max-width: 100%; 
                border-radius: 12px; 
                display: block;
                margin: 0 auto;
              }
              
              .footer { margin-top: 50px; color: #94a3b8; font-size: 12px; border-top: 1px solid #f1f5f9; padding-top: 20px; text-align: center; }
              @media print {
                body { padding: 0; }
                .no-print { display: none; }
              }
            </style>
          </head>
          <body>
            <h1>${document.title}</h1>
            <div class="content">
              ${contentHtml}
            </div>
            <div class="footer">
              Generated by Nordic Slate Editor • ${new Date().toLocaleDateString()}
            </div>
            <script>window.print();</script>
          </body>
        </html>
      `);
    } else if (format === 'docx') {
      res.setHeader('Content-disposition', `attachment; filename=${document.title || 'document'}.docx`);
      res.setHeader('Content-type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
      res.send(`${document.title}\n\n${document.description || ''}`);
    } else {
      res.status(400).json({ error: 'Unsupported format' });
    }
  } catch (error) {
    logger.error(`Error exporting document: ${error}`);
    res.status(500).json({ error: 'Failed to export document' });
  }
});

export default router;
